export const GET_HEADLINES = 'GET_HEADLINES';
export const SEARCH_HEADLINES = 'SEARCH_HEADLINES';
export const HEADLINE_ERROR = 'HEADLINE_ERROR';
export const SAVE_SEARCH_INDEX = 'SAVE_SEARCH_INDEX';


